//autogenerated CHmUsiCk file from SSQlang

Sampler d0;
Sampler d1;
Sampler d2;
Sampler d3;

d0.file("kurt","1");
d1.file("bd","1");
d2.file("hh","1");
d3.file("wobble","1");

spork~d0.soundT([1,0,0,1,0]);
spork~d1.soundT([1,1]);
spork~d2.soundT([0,1,0,1]);
spork~d3.soundT([1,0,0,1]);

2::second => now;
