//autogenerated CHmUsiCk file from SSQlang

Sampler d0;
Sampler d1;
Sampler d2;

d0.file("kurt","1");
d1.file("bd","1");
d2.file("cp","1");

spork~d0.soundC([0,1,0,0,0]);
spork~d1.soundT([1]);
spork~d2.soundC([0,0,1,0]);

2::second => now;
